### ISSUE TITLE
Feature Request: Limited Login

### ISSUE THREAD

**Issue by Luro91** [cordova-plugin-facebook-connect/cordova-plugin-facebook-connect#51]
**Bug or feature request**

[ ] I'm reporting a reproducible issue with the code
[x] I'm reporting a feature request

**Describe the Bug of feature request**

Please integrate Limited Login for iOS: https://developers.facebook.com/docs/facebook-login/limited-login/ios/

**Comment by booleanbetrayal** [comment]
Would also like to support Limited Login in lieu of upcoming disclosure requirements in iOS 14.5 ... Any known workarounds atm?

**Comment by barillax** [comment]
@noahcooper FYI, we've received some guidance that once iOS 14.5 drops in a few weeks, anyone using the Facebook SDK without Limited Login enabled may be required to show the [AppTrackingTransparency pop-up](https://developer.apple.com/app-store/user-privacy-and-data-use/) to request permission to share telemetry data with Facebook or risk having their app releases blocked.

I imagine many developers only wish to use the Facebook SDK for OAuth (and certainly don't want to show the ugly pop-up shown below prior to login). Just wanted to share this since it might impact prioritization of exposing this flag.

![image](https://user-images.githubusercontent.com/29592/114442465-927f0980-9b9a-11eb-9597-c05672ca386d.png)

**Comment by noahcooper** [comment]
I expect to have a new release with support for Limited Login next week.

**Comment by noahcooper** [comment]
As of version 2.3.0 of this plugin, you can now implement Limited Login like so:

```
facebookConnectPlugin.loginWithLimitedTracking(['public_profile', 'email'], 'foo', function(response) {
  console.log('success', response);
}, function(response) {
  console.log('error', response);
});
```

After a user logs in, you can use the new `getCurrentProfile` method to get the user's name and email:

```
facebookConnectPlugin.getCurrentProfile(function(response) {
  console.log('success', response);
}, function(response) {
  console.log('error', response);
});
```

**Comment by barillax** [comment]
Thanks @noahcooper !
