### ISSUE TITLE
[android] facebookConnectPlugin.logout has no effect

### ISSUE THREAD

**Issue by dridri** [cordova-plugin-facebook-connect/cordova-plugin-facebook-connect#71]
Hello,

Calling facebookConnectPlugin.logout() seems to have no effect, even if success callback is triggered.
Logging-in again with facebookConnectPlugin.login() does not show Facebook login-form modal, and directly returns success.
Flushing app cache+data has no effect either.

Even trying to force disconnect right before login has no effect :
```
const next = () => {
	facebookConnectPlugin.login( ["public_profile", "email"], function( result ) {
		console.log( "success", result )
	}, function(error) {
		console.log( "fail", error )
	})
}
facebookConnectPlugin.logout( next, next )
```

What am I missing ?

cordova version : 10.0.0
cordova-android version : 9.0.0
cordova-plugin-facebook-connect version : 2.3.0

**Comment by noahcooper** [comment]
This is expected behavior when the user has the Facebook app installed. The Facebook SDK `logout` method doesn't revoke any previously approved permissions, so when you call `login` again, the Facebook app will open, see that the user has already approved the "public_profile" and "email" permissions, and immediately close itself. (This doesn't happen if the user doesn't have the Facebook app installed -- the browser-based permission page always shows even if the user has already approved the requested permissions.)

The only way to prevent this behavior would be to revoke permissions before calling `login`:

https://developers.facebook.com/docs/facebook-login/permissions/requesting-and-revoking/#revoking

You can use `facebookConnectPlugin.api` to revoke permissions.

**Comment by dridri** [comment]
Oh nice that's perfect, thank you
