### ISSUE TITLE
IOS build failed

### ISSUE THREAD

**Issue by Jasphine** [cordova-plugin-facebook-connect/cordova-plugin-facebook-connect#76]
Hi,

IOS build failed after installed this plugin.

Error:
** BUILD FAILED **
The following build commands failed:
	CompileC /Users/user154019/Library/Developer/Xcode/DerivedData/XXX-cvtevnfptgujrgcklujiiatgpiof/Build/Intermediates.noindex/XXX.build/Debug-iphonesimulator/XXX.build/Objects-normal/x86_64/FacebookConnectPlugin.o XXX/Plugins/cordova-plugin-facebook-connect/FacebookConnectPlugin.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
xcodebuild: Command failed with exit code 65

Cordova : 8.1.2
Cordova-ios : 5.1.1

Thanks and appreciate for your help. Thanks.

**Comment by GexxOn** [comment]
i get the same error

`error: Build input file cannot be found: '/platforms/ios/hokify/Plugins/cordova-plugin-facebook-connect/FacebookConnectPlugin.m' (in target 'xxx' from project 'xxx')`

any ideas?

**Comment by noahcooper** [comment]
@Jasphine This plugin requires `cordova-ios` 6. Can you try again after upgrading? If you're still getting exit code 65, I'd recommend opening the project in Xcode to see the additional details on what error is being thrown.

@GexxOn I don't think your issue is the same. A search online for the error you're encountering seems to suggest that you might've moved things around, and need to reset your workspace in Xcode.
