### ISSUE TITLE
Android build fails after upgrading to android-28

### ISSUE THREAD

**Issue by arthurbic** [cordova-plugin-facebook-connect/cordova-plugin-facebook-connect#90]
Hi, the plugin is working well for iOS but not for Android after I had to upgrade it. All details are here: https://stackoverflow.com/questions/69055797/ionic-build-failed-after-installing-facebook-connect-plugin

**Comment by noahcooper** [comment]
Just responded to you on Stack Overflow. The issue is that as of version 3.1.0 of this plugin, you must use at least `cordova-android@9.0.0`, due to the changes made to address https://github.com/cordova-plugin-facebook-connect/cordova-plugin-facebook-connect/issues/81.

I'll update plugin.xml in the next major release to make this dependency explicit.
